### ISSUE TITLE
Make GL(2,R)-orbit closure computation smarter

### ISSUE THREAD

**Issue by videlec** [flatsurf/sage-flatsurf#41] opened 2020-04-04 17:00 UTC
If we start with a very symmetric locus (such as quadrilateral unfolding), then the search is hard because we have (only) SAF=0 directions where it is hard to guarantee minimality ("complete algebraic periodicity"). As soon as we found one new direction in the tangent space, we should move a little bit in that direction in order to lose this property.

**Comment by saraedum** [comment] 2023-03-17 22:43
This is implemented in flatsurvey in `OrbitClosure._consume()`. However, it's unclear what's a good value for "a little bit" and also which direction to move in directly. If that little bit is too large, a lot of flips are required to make it happen, if it is too small it can lead to coefficient blowup. Also, how quickly the seacrh terminates is extremely sensitive to this deformation in experiments.

**Comment by saraedum** [comment] 2024-11-13 17:25
This is essentially a duplicate of https://github.com/flatsurf/sage-flatsurf/issues/113 and https://github.com/flatsurf/flatsurvey/issues/3.

**Closed by saraedum** 2024-11-13 17:25 UTC
Labels: enhancement
